name: kiosk_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.18.0
  logger: ^2.5.0
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0 # OR RIVE
  shimmer: ^3.0.0
  cached_network_image: ^3.0.0
  video_player: ^2.7.0
  flutter_native_splash: ^2.2.16
  flutter_dotenv: ^5.2.1
  image: ^3.3.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  mqtt_client: ^10.3.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  #Qr Code
  qr_flutter: ^4.1.0

  #Printer
  esc_pos_utils: ^1.1.0
  flutter_pos_printer_platform_image_3:
    path: ./flutter_pos_printer_platform
  encrypt: ^5.0.3
  flutter_localization: ^0.2.1

  #Dropdown package
  dropdown_search: ^5.0.0
  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - .env
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/animations/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
